#!/usr/bin/with-contenv bash

umask 022

cd /opt/lidarr || exit

if [ "$DEBUG" = "NO" ]; then
  	exec \
		s6-setuidgid abc mono Lidarr.exe \
		-nobrowser -data=/config
else
  	exec \
		s6-setuidgid abc mono --debug Lidarr.exe \
		-nobrowser -data=/config
fi

